// Generated by CoffeeScript 1.10.0
(function() {
  var Baobab, Wyre, d3;

  Wyre = {};

  d3 = require('../bower_components/d3/d3.min.js');

  Baobab = require('../bower_components/baobab/build/baobab.min.js');

  Wyre.Manager = require("Manager.coffee");

  window.Wyre = Wyre;

  module.exports = Wyre;

}).call(this);

//# sourceMappingURL=main.js.map
